name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          cd app
          npm install

      - name: Build project
        run: |
          cd app
          npm run build
  
      - name: Move build to /build directory
        run: |
          mv app/build /build
